apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-connection
  namespace: regions-api
spec:
  encryptedData:
    db: AgB0vU5NOCyb9v0raeejhgMbHXVqFaPL5/I6pOHL0kYCNfoc0sARiu168F/IueimwjAY2DiwEUigGf2G+0u5repIqELFeIa6TAhbpto4Fv4YepMCETQNbG3ZXvU0iMy2x/wj51z6Sx8BkrAxZMCW3kJ6WFcu8KbVO1ofJQioQ2mfIdTwo4fuidLBngoFCw6hfzjO9LLHrHkLQDUNiPaJ8rTY0Fyc5WPgv/pN2xCgDwt7p9oZWEtUeOIR2TIbdSY3KtW1n8zG+yxUt2szc4gh/VIXGeMQgHAPl7Wi6Nk2TlrWtcisZNRqQ/v8N7Lk8LOmnigj7QNQOxY+Vxlj9ZnWPrsQTCnu4d6po/Xvw6oZWdpSYKQ2nGrH/zfgriXpNYCdsfj9G7XzDT/14oB8kzRy3MERLaKTO2F6ynF8Ervpkx6WaEtAAKpsCoCgkybv2DMpJabTm/oPQl8Rl3NliHSp6JgP9X0IN3K9NbVYPPbx4vMKCoL4XT0gOfcuvZaljYXTGlgBNO/2TMB0o6gCrQoBvPHqywBoeRZYMDO2oYqCMpyoU+96yQxrVyZIt6Vvd3irbE3wHlOLLrYXaLXCDlGsZfEz+bzwOab22P1Ist8rFsiEUcU6H5s5IplmSzpjIHQxhBCciL5gr9r3Va1fekVMI32xec7ULT3Oq+xU0Bobgo0ZygsFZi+81CGAGUTzNG2quwhe6wTeQsWop7Sp/3Gc6UUy1jKnHVqpJkKE2NHnfOd++hs3GU8vUy+CKsQg4CCGRCf0noYZ4yJKllJPVhpnQIQN6QQccCb+6YWAnQMu8xgQ47lIxUxUfYyjsK3q7leDWF0ZaMFVLIZXvs9yOWHiESN3M3vmxssPQTnnqKJqElDa1b8lLTZReQtiejJBSIfQm+TDHJ0AZbPZZWA=
  template:
    metadata:
      creationTimestamp: null
      name: database-connection
      namespace: regions-api
