---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: treetracker-regions-api
spec:
  cors:
    cors:
    origins:
      - '*'
    headers:
      - Content-Type
      - Authorization
    methods:
      - 'GET, POST, PATCH, PUT, OPTIONS, DELETE'
